# Generated by Django 2.0.2 on 2018-02-26 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_pattern', models.CharField(max_length=128)),
                ('repetition', models.IntegerField()),
                ('chord', models.CharField(max_length=20)),
                ('octave', models.CharField(max_length=3)),
                ('sound', models.CharField(max_length=50)),
                ('bpm', models.IntegerField()),
                ('total_likes', models.IntegerField(default=0)),
                ('total_dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_listened', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequencer.MasterPattern')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(verbose_name='registration date')),
            ],
        ),
    ]
